### ISSUE TITLE
Some tags are not imported

### ISSUE THREAD

**Issue by aserrallerios** [FriendsOfGalaxy/galaxy-integration-steam#28]
Hello,

I want to report that although tags import works, it doesn't import them for all Steam games. I suspect that it happens when a single Steam game belongs to a large amount of Collections.

I'll upload logs if needed.

**Comment by FriendsOfGalaxy** [comment]
Note that currently not all dynamic collection types are supported. Can you show an example and paste your logs to check if it is a bug?

**Comment by FriendsOfGalaxy** [comment]
@aserrallerios  

The way tags work was changed multiple versions back.
Does this issue still occur to you ?

**Comment by aserrallerios** [comment]
It works now after a full metadata import :)

But I'm clueless on what to expect if I remove a tag from a game on steam or if I add a new tag to a game. Should I refresh everything regularly to keep gog on sync?

What about dynamic collections? They don't seem to work now, it's that going to change?

**Comment by FriendsOfGalaxy** [comment]
@aserrallerios  Dynamic collections are more similar to filter settings which are available on Galaxy and right now plugins have no way to setup those or create bookmarks out of them unfortunately, when Galaxy provides such an option i will definitely consider adding dynamic collections.

I'm afraid that any changes made to tags on steam will only be refreshed after you import your metadata again on Galaxy since it doesn't offer a way to auto-sync them.

Both of those things are on Galaxy Client right now.
