### ISSUE TITLE
Password not accepted

### ISSUE THREAD

**Issue by MrLui81** [FriendsOfGalaxy/galaxy-integration-steam#42]
I can't login. My password is correct I just tried on the Steam page. But the plugin refuses the login. Maybe because of the use of !"§$%&/()=?

**Comment by krofinzki** [comment]
I also have this issue, been having it for a week or two now.. maybe longer

**Comment by FriendsOfGalaxy** [comment]
Hello
@MrLui81 
As far as i see its impossible to use § character in your steam password 
![image](https://user-images.githubusercontent.com/48480506/77884384-3a15ec00-7265-11ea-8651-fac4fbad0431.png)
if you have that character in your password maybe its something that was previously allowed by steam and no longer is or maybe its regionalized in which case it would be helpful to know where you are from. 

@MrLui81  @krofinzki 
I've created an account which utilized special characters in its password and everything seems to work fine here, please send me your steam plugin logs found here C:\ProgramData\GOG.com\Galaxy\logs otherwise i won't be able to figure out the issue.  You can attach them here or send them to friendsofgalaxy@gmail.com email.

**Comment by MrLui81** [comment]
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4401685/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

Ok, I'm really using §. I'm from germany.

**Comment by FriendsOfGalaxy** [comment]
Hello again,


i've did some investigation and came upon a suggestion that steam actually
ignores some characters in passwords when authenticating (
https://github.com/winauth/winauth/issues/368)
can you please try logging in again but this time without entering the §
sign (or any other signs which are not included in the basic us keyboard
layout
[image: image.png]
 )

so if your password would be 12@§$er  try entering  12@$er

Hope this helps! if it does i will try implementing a permanent solution to
the problem.
Thanks!

pon., 30 mar 2020 o 10:49 MrLui81 <notifications@github.com> napisał(a):

**Comment by MrLui81** [comment]
Ok strange, that really worked ;)

**Comment by FriendsOfGalaxy** [comment]
Thanks for the confirmation, i will work on a permanent solution then!



wt., 31 mar 2020 o 22:44 MrLui81 <notifications@github.com> napisał(a):

**Comment by krofinzki** [comment]
I'm from Sweden and I had a special character "å" from our character-set. Typing in the password without that one character made it possible to log in!

(Different scandinavian letters: Å,å,Ä,ä,Ö,ö,Æ,æ,Ø,ø)

**Comment by FriendsOfGalaxy** [comment]
Fix is ready and the next release of the plugin will include it. Thank you guys for the report!
