### ISSUE TITLE
would it be possible to add 2 or more steam acounts ?

### ISSUE THREAD

**Issue by Manni1000** [FriendsOfGalaxy/galaxy-integration-steam#59]
hi would it be possible to add 2 or more steam acounts ?

**Comment by FriendsOfGalaxy** [comment]
Hi @Manni1000 ,

i'm not sure i understand the reasoning for this. If you want to see games from both accounts why not use family sharing ( games retrieved from it will shown in the subscriptions tab in Galaxy)

**Comment by Pingger** [comment]
Hi,

@FriendsOfGalaxy 
Reason 1: Family sharing doesn't work for quite a few games, because the Publishers block it.
Reason 2: I maintain different Friendlists per Account. As soon as GOG Crossplaform chat finally works, it would be nice to interact on multiple accounts.
Reason 3: My family shared games from other accounts are not displayed in the subscription tab. They aren't displayed at all anywhere, nor are the achievements and time available.

need more reasons?
I have seen this asked at several places in the past and the answer has always been: "You wouldn't use it anyway" or "That's stupid"

Greetings

**Comment by FriendsOfGalaxy** [comment]
@Pingger on second though I agree with you and all those other people - such feature would be really cool.

However I'm affraid it is out of the scope of this project, for following reasons:
- it is against design of the GOG Galaxy API interface - in other words we have no support for multiple accounts natively (like authentication interface)
- even if plugin could theoretically hack on current Galaxy API interface and gather multiple accounts info as an artificial one account - this requires huge amount of work
- we already have big problems with keeping ONE user authentication not speaking about more

So IMO the more probable way to complete this feature request is:
1. though support in Galaxy either in the API design or by enabling running multiple plugin instances (spam their whishlist if you like)
2. some kind of hack-ish plugin-wrapper that would be separate smart project that would run multiple plugins under the hood and talk with Galaxy as an only one plugin.
3. hack inside different implementation of steam plugin (simpler one than this, see https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/2#issuecomment-763611560). Current implementation mocks Steam protocols - the same which Steam app is using. Even Steam app does not try to support multiple accounts
