### ISSUE TITLE
Custom cover art for Steam games keep resetting

### ISSUE THREAD

**Issue by OpenRift412** [FriendsOfGalaxy/galaxy-integration-steam#71]
It seems that every time I restart GOG Galaxy, it will reset my custom cover art for the same handful of games, which I've found are all on Steam. The strange thing is, it doesn't reset all of my custom cover art, just certain ones. Namely, Doom 3, several of the Serious Sam games, Wrath: Aeon of Ruin, Totally Accurate Battlegrounds, Unfortunate Spacemen, and Maximum Action, to name a few.

**To Reproduce**
<Remove this section if it's obvious>
Steps to reproduce the behavior, for example:
1. Set custom cover art for games
2. Restart Galaxy
3. Sync integrations
4. Go to your recently customized cover art and wait.

**Expected behavior**
As You could probably guess, it's supposed to save my custom cover art like my other games, but it decides not to.

**Attached logs**
This log should be around the time that it happened most recently.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4833428/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
@OpenRift412 
There are 2 ways to provide games to galaxy client,
one is batch sending as a response to owned_games call
one is calling add_game for anything that we won't be able to send in time for the batch call.

I can see that the games you have problem with were sent using the add_game signal. There's honestly nothing i can do plugin side to stop the covers from resetting, it seems like a problem with logic on the side of galaxy, they probably discard custom stuff for games which weren't provided in the batch response.

Your best bet is to report this issue here https://mantis2.gog.com along with my comment.
