### ISSUE TITLE
Steam: Offline Retry.

### ISSUE THREAD

**Issue by fabiofs-br** [FriendsOfGalaxy/galaxy-integration-steam#8]
Since I installed GOG Galaxy 2.0 I'm unable to connect to Steam. I dont know what maybe causing this but my log follows below.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3576836/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by CodenameReese** [comment]
Since I also had this issue I thought I would give my solution:
It seems the plugin is trying to get the steamId (and more?) from the user's steam profile page, thus if you haven't created one it gives this error ("Can not parse backend response - no div.profile_header_centered_persona"). 
Luckily I just had to create one in Steam and now everything seems to be working fine, even though I marked everything as private in Steam's profile privacy settings.
I have no idea though if this is avoidable somehow.

**Comment by fabiofs-br** [comment]
> Since I also had this issue I thought I would give my solution:
> It seems the plugin is trying to get the steamId (and more?) from the user's steam profile page, thus if you haven't created one it gives this error ("Can not parse backend response - no div.profile_header_centered_persona").
> I just had to create one in Steam and now everything seems to be working fine, even though I marked everything as "private" in Steam's profile privacy settings (whatever private means in this case)
> I have no idea though if this is avoidable somehow.

This solved the problem in fact. I'm not a huge Steam user so I didn't created any steamId either. Steam is working as intended now.
